name: quality/document-validation

on:
  pull_request:
    branches: [ main, '*_in_lavorazione' ]
  push:
    branches: [ main, '*_in_lavorazione' ]

jobs:
  # Questo è il nome che cercherai nelle impostazioni di Branch Protection
  document-validation:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-extra texlive-lang-italian aspell aspell-it

      - name: Get changed .tex files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/*.tex

      - name: Run Validation Script
        if: steps.changed-files.outputs.any_changed == 'true'
        # Lo script analizzerà solo i file .tex modificati
        run: python3 scripts/check_docs.py ${{ steps.changed-files.outputs.all_changed_files }}